name: push-pipeline
on:
  push:
    branches:
      - master
      - ^v[0-9]*.[0-9]*.x$
    tags:
      - "*"
      
jobs:

  get-envs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - run: |
          echo export IMG_TAG="ci" >> env-vars
          echo export GRAPHQL_SERVER_IMAGE="litmusportal-server" >> env-vars
          echo export AUTHENTICATION_SERVER_IMAGE="litmusportal-auth-server" >> env-vars
          echo export FRONTEND_IMAGE="litmusportal-frontend" >> env-vars
          echo export SUBSCRIBER_IMAGE="litmusportal-subscriber" >> env-vars
          echo export EVENT_TRACKER="litmusportal-event-tracker" >> env-vars

      - name: Uploading envs
        uses: actions/upload-artifact@v2
        with:
          name: env_artifact
          path: litmus-portal/env-vars

  ## TODO: the build time for multiarch frontend image is higher so it is used in the release
  ## builds only need to optimize the build duration and also add it with ci tag
  ## Build and push / base path
  docker-build-and-push-frontend:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
          path: litmus-portal

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push frontend docker image (/)
        env:
          FRONTEND_IMAGE: ${FRONTEND_IMAGE}
          IMG_TAG: ${IMG_TAG}
          PLATFORMS: "amd64"
          REPONAME: "jonsy13"
          timestamp: ${timestamp}
          PUBLIC_URL: ""
        run: |
          source env-vars
          timestamp=`date "+%s"`
          make push-frontend


  ## TODO: the build time for multiarch frontend image is higher so it is used in the release
  ## builds only need to optimize the build duration and also add it with ci tag 
  ## Build and push /litmuschaos base path
  docker-build-and-push-frontend-litmuschaos-basepath:
    runs-on: ubuntu-latest
    needs:
      - get-envs
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Downloading image artficate
        uses: actions/download-artifact@v2
        with:
          name: env_artifact
          path: litmus-portal

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push frontend docker image (/litmuschaos)
        env:
          IMG_TAG: ${IMG_TAG}
          PLATFORMS: "amd64"
          REPONAME: "jonsy13"
          timestamp: ${timestamp}
          PUBLIC_URL: "/litmuschaos"
        run: |
          source env-vars
          export FRONTEND_IMAGE="litmusportal-frontend-path-litmuschaos"
          timestamp=`date "+%s"`
          make push-frontend